# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c43d887a79c2b77030fe27b4cac3c202644f153ff8705387192a01303b21205757daf4ca5b5d59617b7bf39d9fba3c9639cdc2e5dac9371fad00c6abcb977d4c

test:
  secret_key_base: 851d7091afb00409dd1357bff0a506d2a6dfd5741a6bf08c25a77aec5cd12becb88d34b4fee4681d5d8d62e4cf340a220e799b5a174dfc127790dfcb37974427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
