
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c43d887a79c2b77030fe27b4cac3c202644f153ff8705387192a01303b21205757daf4ca5b5d59617b7bf39d9fba3c9639cdc2e5dac9371fad00c6abcb977d4c
  stripe_public_key: pk_test_PvONDGQ1XNotz82t4lU9AXAe
  stripe_secret_key: sk_test_4SMmTVoMVqK6jAEI3xXYVUVH
  omniauth_facebook_app_key: 8c616fa2d86cee4845022bea02823052
  omniauth_facebook_app_id: "693132877402583"
  s3_access_key: AKIAJ5IRY3IR4IHFAFMA
  s3_secret_key: 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
  omniauth_google_client_id: 979643794276-65t37nf5n7do1hlvjq0g1fkhirf4h71u.apps.googleusercontent.com
  omniauth_google_client_secret: 9ehDNK4t0mkqfNOdKJYkh5u3

test:
  secret_key_base: 851d7091afb00409dd1357bff0a506d2a6dfd5741a6bf08c25a77aec5cd12becb88d34b4fee4681d5d8d62e4cf340a220e799b5a174dfc127790dfcb37974427
  stripe_public_key: PvONDGQ1XNotz82t4lU9AXAe
  stripe_secret_key: 4SMmTVoMVqK6jAEI3xXYVUVH
  omniauth_facebook_app_key: 8c616fa2d86cee4845022bea02823052
  omniauth_facebook_app_id: "693132877402583"
  s3_access_key: AKIAJ5IRY3IR4IHFAFMA
  s3_secret_key: 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
  omniauth_google_client_id: 979643794276-65t37nf5n7do1hlvjq0g1fkhirf4h71u.apps.googleusercontent.com
  omniauth_google_client_secret: 9ehDNK4t0mkqfNOdKJYkh5u3



# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: dc48ddb2953755cdf254f2dd5b2ffed8647f51fd53ffc3a51cf473d0b3456cd9e50ff941502721f70fd287e763330775064aa448d410f37c9cc56eb251cd22c3
  stripe_public_key: pk_test_PvONDGQ1XNotz82t4lU9AXAe
  stripe_secret_key: sk_test_4SMmTVoMVqK6jAEI3xXYVUVH